# Generated by Django 3.0.5 on 2020-05-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0003_auto_20200509_1229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_sign_up',
        ),
    ]
